# Generated by Django 4.2 on 2024-08-17 04:16

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='defaults/profile_pic/default_profile_pic', null=True, upload_to=account.models.return_path),
        ),
    ]
