# Generated by Django 4.2 on 2024-08-17 04:19

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='defaults/profile_pic/default_profile_pic', upload_to=account.models.return_path),
        ),
    ]
