# Generated by Django 4.2 on 2024-08-17 05:04

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='defaults/profile_pic/default-profile-pic.png', upload_to=account.models.return_path),
        ),
    ]
