# Generated by Django 4.2 on 2024-08-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='subscriptionId',
            field=models.CharField(default=None, max_length=100000000000000),
        ),
    ]
