# Generated by Django 4.2 on 2024-08-12 23:13

from django.db import migrations, models
import subscriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_usersubscription_subscriptionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=subscriptions.models.photo_path),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
