# Generated by Django 4.2 on 2024-08-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionplan_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='display_color',
            field=models.CharField(default='#FFFFFF', max_length=10),
        ),
    ]
