# Generated by Django 4.2 on 2024-08-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscriptionplan_display_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='alt_display_color',
            field=models.CharField(default='#000000', max_length=10),
        ),
    ]
