# Generated by Django 4.2 on 2024-09-11 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_usersubscription_starting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='no_of_days',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='duration',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='starting_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 9, 11, 12, 55, 0, 33717)),
        ),
    ]
