# Generated by Django 4.2 on 2024-09-11 15:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
import subscriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_remove_usersubscription_no_of_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='starting_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 9, 11, 16, 42, 5, 550041)),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=6)),
                ('occupied', models.BooleanField(default=False)),
                ('room_class', models.ForeignKey(default=subscriptions.models.Room.model_default, on_delete=django.db.models.deletion.SET_DEFAULT, to='subscriptions.subscriptionplan')),
            ],
        ),
    ]
