# Generated by Django 4.2 on 2024-09-11 21:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import subscriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_usersubscription_starting_date_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='room',
            field=models.ForeignKey(default=subscriptions.models.UserSubscription.room_default, on_delete=django.db.models.deletion.SET_DEFAULT, to='subscriptions.room'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='starting_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 9, 11, 22, 23, 32, 453735)),
        ),
    ]
