# Generated by Django 4.2 on 2024-09-11 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_usersubscription_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='starting_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 9, 11, 22, 25, 25, 255574)),
        ),
    ]
