# Generated by Django 4.2 on 2024-09-12 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_alter_usersubscription_starting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='starting_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 9, 12, 9, 31, 18, 658777)),
        ),
    ]
