# Generated by Django 4.2 on 2024-09-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_alter_usersubscription_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='price',
        ),
    ]
