# Generated by Django 4.2 on 2024-09-20 15:55

from django.db import migrations, models
import django.db.models.deletion
import subscriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0020_alter_usersubscription_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='room',
            field=models.OneToOneField(default=subscriptions.models.UserSubscription.room_default, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.room'),
        ),
    ]
