# Generated by Django 4.2 on 2026-03-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0022_alter_usersubscription_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
