# Generated by Django 4.2 on 2026-03-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0023_alter_subscriptionplan_price_per_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
