# Generated by Django 4.2 on 2026-03-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0024_alter_subscriptionplan_price_per_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='subscriptionId',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
