# Generated by Django 4.2 on 2026-03-21 21:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0025_alter_usersubscription_subscriptionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
