# Generated by Django 4.2 on 2024-09-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_payments', '0002_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
