# Generated by Django 4.2 on 2024-09-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_payments', '0003_alter_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='client_id',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
