# Generated by Django 4.2 on 2024-09-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_payments', '0005_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='model_paid_for',
            field=models.JSONField(default=dict),
        ),
    ]
