# Generated by Django 4.2 on 2024-10-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_payments', '0006_payment_model_paid_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='callback_code',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
