# Generated by Django 4.2 on 2024-10-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_payments', '0007_payment_callback_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='callback_code',
            field=models.CharField(max_length=10),
        ),
    ]
